apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ${KRUIZE_UI_NAMESPACE}
data:
  nginx.conf: |
    events {}
    http {
      upstream kruize-api {
        server kruize:8080;
      }

      server {
        listen 8080;
        server_name localhost;

        root   /usr/share/nginx/html;
        
        location ^~ /api/ {
          rewrite ^/api(.*)$ $1 break;
          proxy_pass http://kruize-api;
        }
    
        location / {
          index index.html;
          error_page 404 =200 /index.html;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: kruize-ui-nginx-service
  namespace: ${KRUIZE_UI_NAMESPACE}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: kruize-ui-nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: kruize-ui-nginx-pod
  namespace: ${KRUIZE_UI_NAMESPACE}
  labels:
    app: kruize-ui-nginx
spec:
  containers:
    - name: kruize-ui-nginx-container
      image: ${KRUIZE_UI_IMAGE}
      imagePullPolicy: Always
      env:
      - name: KRUIZE_UI_ENV
        value: "production"
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
